### ISSUE TITLE
How can I run it for project.clj?

### ISSUE THREAD

**Issue by nbotelhodev** [ertugrulcetin/lein-nsort#1]
Hi,

I really liked this plugin, congrats! Thank you, it's very useful.

Can you help me to run for project.clj?

I've tried this without successfull:

```
:nsort {:require :asc ;;(default)
          :import  :desc
          :source-paths [ "." "<project's name>" "src/.."]
          })
```

**Comment by ertugrulcetin** [comment]
Hi @nbotelhodev, I'm glad that you liked it! Unfortunately, lein-nsort does not support project.clj deps :(
